project:
  type: website
  preview:
    port: 4000
    browser: true
  output-dir: docs

title: "Maximal Onset Principle as a cue for syllable detection at birth"
format:
  prezconf-revealjs:
    self-contained: false
    from: markdown+emoji
    transition: fade
    progress: true
    preload-iframes: true
    link-external-newwindow: true
    github: gongcastro

authors:
  - Gonzalo<br>García-Castro
  - Laura S.<br>Piracún-García
  - Chiara<br>Santolin

resources: 
    - "img/setup.mp4"
    - "sounds/st-block.mp4"
    - "sounds/dw-block.mp4"
    - "sounds/ds-block.mp4"

echo: false
warning: false
fig-dpi: 800

bibliography: references.bib
scrollable: true
show-slide-number: all
slide-number: c
date: "2025-04-29"
conference: sap-2025-mop-newborns
