project:
  preview:
    port: 4000
    browser: true
  output-dir: docs

title: "Maximal Onset Principle as a cue for syllable detection at birth"
format:
  prezconf-revealjs:
    self-contained: true
    from: markdown+emoji
    transition: fade
    progress: true
    preload-iframes: true
    link-external-newwindow: true
    github: gongcastro
  pptx: default

echo: false
warning: false
fig-dpi: 800

bibliography: references.bib
scrollable: true
show-slide-number: all
slide-number: c
date: "2025-04-29"
conference: sap2025-mop-newborns
